services:
  # MongoDB Database Service
  mongodb:
    image: mongo:7-jammy
    container_name: payment-later-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-payment_later_dev}
    volumes:
      - mongodb_data_dev:/data/db
      - mongodb_config_dev:/data/configdb
      - ./docker/mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - payment-later-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # PaymentLaterAPI Application Service
  payment-later-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: payment-later-api-dev
    restart: unless-stopped
    ports:
      - "1010:1010"
    environment:
      # Database Configuration
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/${MONGO_DATABASE:-payment_later_dev}?authSource=admin
      MONGODB_DATABASE: ${MONGO_DATABASE:-payment_later_dev}
      
      # JWT Configuration (Base64 encoded secret - set in .env file!)
      JWT_SECRET_BASE64: ${JWT_SECRET_BASE64:-ZGV2ZWxvcG1lbnQtand0LXNlY3JldC1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9uLXRoaXMtaXMtbm90LXNlY3VyZS1mb3ItcHJvZHVjdGlvbg==}
      
      # Mail Configuration (set in .env file!)
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL:-your-email@gmail.com}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD:-your-app-password}
      
      # Spring Profile
      SPRING_PROFILES_ACTIVE: dev
      
      # Logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_BLAISE: DEBUG
    volumes:
      # For development: mount source code for hot reload (optional)
      - ./src:/app/src:ro
      - ./build.gradle.kts:/app/build.gradle.kts:ro
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - payment-later-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1010/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MongoDB Express (Web-based MongoDB admin interface) - Development only
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: payment-later-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - payment-later-network
    profiles:
      - tools

volumes:
  mongodb_data_dev:
    driver: local
  mongodb_config_dev:
    driver: local

networks:
  payment-later-network:
    driver: bridge